/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Product } from '../../shared/types.js';

export const STORE_AISLES = [
  { number: 1, name: 'Fresh Produce', coordinate: { x: 20, y: 30 }, category: 'Produce' },
  { number: 2, name: 'Artisan Bakery', coordinate: { x: 20, y: 70 }, category: 'Bakery' },
  { number: 3, name: 'Dairy & Plant Milks', coordinate: { x: 45, y: 30 }, category: 'Dairy & Eggs' },
  { number: 4, name: 'Pantry, Grains & Oils', coordinate: { x: 45, y: 70 }, category: 'Pantry & Grains' },
  { number: 5, name: 'Butcher & Plant Proteins', coordinate: { x: 70, y: 30 }, category: 'Meat & Seafood' },
  { number: 6, name: 'Frozen Goods & Meals', coordinate: { x: 70, y: 70 }, category: 'Frozen' },
  { number: 7, name: 'Beverages & Hydration', coordinate: { x: 90, y: 30 }, category: 'Beverages' },
  { number: 8, name: 'Healthy Snacks & Nuts', coordinate: { x: 90, y: 70 }, category: 'Snacks' },
];

export const INITIAL_PRODUCTS: Product[] = [
  // Aisle 1 - Produce
  {
    id: 'prod-001',
    name: 'Organic Hass Avocados (4-Pack)',
    brand: 'GreenMeadow Farms',
    category: 'Produce',
    price: 4.49,
    originalPrice: 5.29,
    unit: 'bag',
    barcode: '01111000101',
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 1 - Fresh Produce',
    aisleNumber: 1,
    shelfSection: 'Shelf 1A - Tropical Fruits',
    coordinates: { x: 18, y: 25 },
    dietaryFlags: ['vegan', 'gluten-free', 'keto'],
    allergens: [],
    nutrition: { calories: 160, proteinGrams: 2, carbsGrams: 9, fatGrams: 15, fiberGrams: 7, sodiumMg: 7 },
    inStock: true,
    stockCount: 84,
    weightGrams: 600,
    ecoScore: 'A',
  },
  {
    id: 'prod-002',
    name: 'Organic Honeycrisp Apples',
    brand: 'Orchard Valley',
    category: 'Produce',
    price: 3.99,
    unit: '2 lb bag',
    barcode: '01111000102',
    imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 1 - Fresh Produce',
    aisleNumber: 1,
    shelfSection: 'Shelf 1B - Domestic Orchards',
    coordinates: { x: 22, y: 28 },
    dietaryFlags: ['vegan', 'gluten-free', 'low-sodium'],
    allergens: [],
    nutrition: { calories: 95, proteinGrams: 0.5, carbsGrams: 25, fatGrams: 0.3, fiberGrams: 4.4, sodiumMg: 2 },
    inStock: true,
    stockCount: 110,
    weightGrams: 900,
    ecoScore: 'A',
  },
  {
    id: 'prod-003',
    name: 'Organic Baby Spinach Leaves',
    brand: 'Earthbound Greens',
    category: 'Produce',
    price: 3.29,
    originalPrice: 3.79,
    unit: '16 oz tub',
    barcode: '01111000103',
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 1 - Fresh Produce',
    aisleNumber: 1,
    shelfSection: 'Shelf 1C - Chilled Salads',
    coordinates: { x: 20, y: 35 },
    dietaryFlags: ['vegan', 'gluten-free', 'keto', 'low-sodium'],
    allergens: [],
    nutrition: { calories: 23, proteinGrams: 2.9, carbsGrams: 3.6, fatGrams: 0.4, fiberGrams: 2.2, sodiumMg: 79 },
    inStock: true,
    stockCount: 45,
    weightGrams: 454,
    ecoScore: 'A',
  },

  // Aisle 2 - Bakery
  {
    id: 'prod-004',
    name: 'Artisan San Francisco Sourdough Loaf',
    brand: 'Golden Crust Bakery',
    category: 'Bakery',
    price: 4.89,
    unit: 'loaf (24 oz)',
    barcode: '01111000201',
    imageUrl: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 2 - Artisan Bakery',
    aisleNumber: 2,
    shelfSection: 'Shelf 2A - Fresh Daily Breads',
    coordinates: { x: 19, y: 65 },
    dietaryFlags: ['vegan', 'vegetarian'],
    allergens: ['wheat'],
    nutrition: { calories: 140, proteinGrams: 5, carbsGrams: 28, fatGrams: 1, fiberGrams: 1.5, sodiumMg: 280 },
    inStock: true,
    stockCount: 22,
    weightGrams: 680,
    ecoScore: 'B',
  },
  {
    id: 'prod-005',
    name: 'Gluten-Free Seeded Ancient Grain Bread',
    brand: 'Canyon River Bakeries',
    category: 'Bakery',
    price: 6.49,
    unit: 'loaf (18 oz)',
    barcode: '01111000202',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 2 - Artisan Bakery',
    aisleNumber: 2,
    shelfSection: 'Shelf 2C - Gluten Free Specialty',
    coordinates: { x: 22, y: 75 },
    dietaryFlags: ['gluten-free', 'dairy-free', 'vegetarian'],
    allergens: ['sesame', 'eggs'],
    nutrition: { calories: 120, proteinGrams: 3, carbsGrams: 22, fatGrams: 2.5, fiberGrams: 3, sodiumMg: 190 },
    inStock: true,
    stockCount: 18,
    weightGrams: 510,
    ecoScore: 'B',
  },

  // Aisle 3 - Dairy & Plant Milks
  {
    id: 'prod-006',
    name: 'Pasture-Raised Organic Whole Milk',
    brand: 'Clover Pastures',
    category: 'Dairy & Eggs',
    price: 4.99,
    unit: 'half-gallon',
    barcode: '01111000301',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 3 - Dairy & Plant Milks',
    aisleNumber: 3,
    shelfSection: 'Shelf 3A - Cold Dairy Cases',
    coordinates: { x: 44, y: 25 },
    dietaryFlags: ['vegetarian', 'gluten-free', 'keto'],
    allergens: ['dairy'],
    nutrition: { calories: 150, proteinGrams: 8, carbsGrams: 12, fatGrams: 8, sodiumMg: 125 },
    inStock: true,
    stockCount: 50,
    weightGrams: 1900,
    ecoScore: 'B',
  },
  {
    id: 'prod-007',
    name: 'Barista Organic Oat Milk (Unsweetened)',
    brand: 'OatHaven Botanicals',
    category: 'Dairy & Eggs',
    price: 4.49,
    originalPrice: 4.99,
    unit: '64 fl oz',
    barcode: '01111000302',
    imageUrl: 'https://images.unsplash.com/photo-1596797882870-8c33deeac224?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 3 - Dairy & Plant Milks',
    aisleNumber: 3,
    shelfSection: 'Shelf 3B - Plant Milks',
    coordinates: { x: 47, y: 28 },
    dietaryFlags: ['vegan', 'dairy-free', 'nut-free', 'vegetarian'],
    allergens: [],
    nutrition: { calories: 120, proteinGrams: 3, carbsGrams: 16, fatGrams: 5, fiberGrams: 2, sodiumMg: 100 },
    inStock: true,
    stockCount: 65,
    weightGrams: 1850,
    ecoScore: 'A',
  },
  {
    id: 'prod-008',
    name: 'Certified Humane Pasture-Raised Brown Eggs (1 Dozen)',
    brand: 'Vital Roost',
    category: 'Dairy & Eggs',
    price: 5.79,
    unit: '12 count',
    barcode: '01111000303',
    imageUrl: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 3 - Dairy & Plant Milks',
    aisleNumber: 3,
    shelfSection: 'Shelf 3C - Farm Fresh Eggs',
    coordinates: { x: 45, y: 35 },
    dietaryFlags: ['keto', 'gluten-free', 'dairy-free', 'vegetarian'],
    allergens: ['eggs'],
    nutrition: { calories: 70, proteinGrams: 6, carbsGrams: 0, fatGrams: 5, sodiumMg: 70 },
    inStock: true,
    stockCount: 70,
    weightGrams: 720,
    ecoScore: 'A',
  },
  {
    id: 'prod-009',
    name: 'Greek Whole Milk Strained Yogurt (Plain)',
    brand: 'Olympian Peak',
    category: 'Dairy & Eggs',
    price: 5.19,
    unit: '32 oz tub',
    barcode: '01111000304',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 3 - Dairy & Plant Milks',
    aisleNumber: 3,
    shelfSection: 'Shelf 3D - Yogurts & Kefir',
    coordinates: { x: 46, y: 38 },
    dietaryFlags: ['vegetarian', 'gluten-free', 'keto'],
    allergens: ['dairy'],
    nutrition: { calories: 170, proteinGrams: 18, carbsGrams: 6, fatGrams: 9, sodiumMg: 65 },
    inStock: true,
    stockCount: 38,
    weightGrams: 907,
    ecoScore: 'B',
  },

  // Aisle 4 - Pantry & Grains
  {
    id: 'prod-010',
    name: 'Extra Virgin Cold Pressed Olive Oil',
    brand: 'Tuscan Groves Reserve',
    category: 'Pantry & Grains',
    price: 13.99,
    originalPrice: 15.99,
    unit: '750 ml bottle',
    barcode: '01111000401',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 4 - Pantry, Grains & Oils',
    aisleNumber: 4,
    shelfSection: 'Shelf 4A - Specialty Oils & Vinegars',
    coordinates: { x: 44, y: 65 },
    dietaryFlags: ['vegan', 'keto', 'gluten-free'],
    allergens: [],
    nutrition: { calories: 120, proteinGrams: 0, carbsGrams: 0, fatGrams: 14, sodiumMg: 0 },
    inStock: true,
    stockCount: 40,
    weightGrams: 800,
    ecoScore: 'A',
  },
  {
    id: 'prod-011',
    name: 'Organic Tricolor Quinoa (Peruvian)',
    brand: 'Andean Gold',
    category: 'Pantry & Grains',
    price: 4.69,
    unit: '16 oz bag',
    barcode: '01111000402',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 4 - Pantry, Grains & Oils',
    aisleNumber: 4,
    shelfSection: 'Shelf 4B - Ancient Grains',
    coordinates: { x: 46, y: 70 },
    dietaryFlags: ['vegan', 'gluten-free', 'kosher'],
    allergens: [],
    nutrition: { calories: 170, proteinGrams: 6, carbsGrams: 30, fatGrams: 2.5, fiberGrams: 3, sodiumMg: 5 },
    inStock: true,
    stockCount: 58,
    weightGrams: 454,
    ecoScore: 'A',
  },
  {
    id: 'prod-012',
    name: 'San Marzano DOP Whole Peeled Tomatoes',
    brand: 'Campania Heritage',
    category: 'Pantry & Grains',
    price: 4.29,
    unit: '28 oz can',
    barcode: '01111000403',
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 4 - Pantry, Grains & Oils',
    aisleNumber: 4,
    shelfSection: 'Shelf 4C - Canned Tomatoes & Sauces',
    coordinates: { x: 47, y: 75 },
    dietaryFlags: ['vegan', 'gluten-free', 'low-sodium'],
    allergens: [],
    nutrition: { calories: 30, proteinGrams: 1.5, carbsGrams: 6, fatGrams: 0, fiberGrams: 1.5, sodiumMg: 140 },
    inStock: true,
    stockCount: 92,
    weightGrams: 794,
    ecoScore: 'B',
  },

  // Aisle 5 - Meat & Seafood
  {
    id: 'prod-013',
    name: 'Organic Boneless Skinless Chicken Breast',
    brand: 'Bell & Evans Heritage',
    category: 'Meat & Seafood',
    price: 8.99,
    unit: '1.2 lb tray',
    barcode: '01111000501',
    imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 5 - Butcher & Plant Proteins',
    aisleNumber: 5,
    shelfSection: 'Shelf 5A - Poultry Fresh Cut',
    coordinates: { x: 69, y: 25 },
    dietaryFlags: ['keto', 'gluten-free', 'dairy-free'],
    allergens: [],
    nutrition: { calories: 120, proteinGrams: 26, carbsGrams: 0, fatGrams: 1.5, sodiumMg: 75 },
    inStock: true,
    stockCount: 30,
    weightGrams: 544,
    ecoScore: 'C',
  },
  {
    id: 'prod-014',
    name: 'Wild-Caught Alaskan Sockeye Salmon Fillet',
    brand: 'Pacific Cold Current',
    category: 'Meat & Seafood',
    price: 12.49,
    originalPrice: 14.99,
    unit: '1 lb fresh fillet',
    barcode: '01111000502',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 5 - Butcher & Plant Proteins',
    aisleNumber: 5,
    shelfSection: 'Shelf 5B - Sustainable Seafood',
    coordinates: { x: 71, y: 30 },
    dietaryFlags: ['keto', 'gluten-free', 'dairy-free'],
    allergens: ['fish'],
    nutrition: { calories: 180, proteinGrams: 24, carbsGrams: 0, fatGrams: 9, sodiumMg: 65 },
    inStock: true,
    stockCount: 25,
    weightGrams: 454,
    ecoScore: 'A',
  },
  {
    id: 'prod-015',
    name: 'Organic Sprouted Extra Firm Tofu',
    brand: 'Wildwood Organics',
    category: 'Meat & Seafood',
    price: 2.99,
    unit: '15.5 oz pack',
    barcode: '01111000503',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 5 - Butcher & Plant Proteins',
    aisleNumber: 5,
    shelfSection: 'Shelf 5C - Plant Protein Alternatives',
    coordinates: { x: 70, y: 38 },
    dietaryFlags: ['vegan', 'gluten-free', 'keto'],
    allergens: ['soy'],
    nutrition: { calories: 130, proteinGrams: 14, carbsGrams: 2, fatGrams: 7, sodiumMg: 15 },
    inStock: true,
    stockCount: 45,
    weightGrams: 440,
    ecoScore: 'A',
  },

  // Aisle 6 - Frozen
  {
    id: 'prod-016',
    name: 'Organic Wild Blueberries (IQF Frozen)',
    brand: 'Wyman’s Maine Harvest',
    category: 'Frozen',
    price: 4.99,
    unit: '15 oz bag',
    barcode: '01111000601',
    imageUrl: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 6 - Frozen Goods & Meals',
    aisleNumber: 6,
    shelfSection: 'Shelf 6A - Frozen Fruits & Smoothie Blends',
    coordinates: { x: 69, y: 65 },
    dietaryFlags: ['vegan', 'gluten-free'],
    allergens: [],
    nutrition: { calories: 80, proteinGrams: 1, carbsGrams: 18, fatGrams: 0.5, fiberGrams: 4, sodiumMg: 0 },
    inStock: true,
    stockCount: 60,
    weightGrams: 425,
    ecoScore: 'A',
  },
  {
    id: 'prod-017',
    name: 'Cauliflower Crust Margherita Pizza',
    brand: 'CauliCrafters Gourmet',
    category: 'Frozen',
    price: 7.99,
    originalPrice: 8.99,
    unit: '12-inch pizza',
    barcode: '01111000602',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 6 - Frozen Goods & Meals',
    aisleNumber: 6,
    shelfSection: 'Shelf 6B - Healthy Frozen Entrees',
    coordinates: { x: 72, y: 72 },
    dietaryFlags: ['gluten-free', 'vegetarian'],
    allergens: ['dairy', 'eggs'],
    nutrition: { calories: 330, proteinGrams: 14, carbsGrams: 28, fatGrams: 16, fiberGrams: 3, sodiumMg: 590 },
    inStock: true,
    stockCount: 35,
    weightGrams: 380,
    ecoScore: 'B',
  },

  // Aisle 7 - Beverages
  {
    id: 'prod-018',
    name: 'Sparkling Mineral Water (Blood Orange)',
    brand: 'San Pellegrino Essenza',
    category: 'Beverages',
    price: 5.99,
    unit: '8-pack slim cans',
    barcode: '01111000701',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 7 - Beverages & Hydration',
    aisleNumber: 7,
    shelfSection: 'Shelf 7A - Sparkling & Mineral Waters',
    coordinates: { x: 89, y: 25 },
    dietaryFlags: ['vegan', 'gluten-free', 'sugar-free', 'keto'],
    allergens: [],
    nutrition: { calories: 0, proteinGrams: 0, carbsGrams: 0, fatGrams: 0, sodiumMg: 0 },
    inStock: true,
    stockCount: 88,
    weightGrams: 2600,
    ecoScore: 'B',
  },
  {
    id: 'prod-019',
    name: 'Organic Cold-Pressed Green Immunity Juice',
    brand: 'Daily Roots Botanicals',
    category: 'Beverages',
    price: 6.29,
    unit: '16 fl oz bottle',
    barcode: '01111000702',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 7 - Beverages & Hydration',
    aisleNumber: 7,
    shelfSection: 'Shelf 7B - Chilled Cold Pressed',
    coordinates: { x: 91, y: 35 },
    dietaryFlags: ['vegan', 'gluten-free'],
    allergens: [],
    nutrition: { calories: 110, proteinGrams: 2, carbsGrams: 24, fatGrams: 0.5, fiberGrams: 1, sodiumMg: 65 },
    inStock: true,
    stockCount: 40,
    weightGrams: 470,
    ecoScore: 'A',
  },

  // Aisle 8 - Snacks
  {
    id: 'prod-020',
    name: 'Raw California Almonds (Unsalted)',
    brand: 'NutriSun Orchard',
    category: 'Snacks',
    price: 7.49,
    originalPrice: 8.99,
    unit: '16 oz resealable bag',
    barcode: '01111000801',
    imageUrl: 'https://images.unsplash.com/photo-1508061252445-5350f3ab0a55?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 8 - Healthy Snacks & Nuts',
    aisleNumber: 8,
    shelfSection: 'Shelf 8A - Bulk Organic Nuts',
    coordinates: { x: 89, y: 65 },
    dietaryFlags: ['vegan', 'gluten-free', 'keto', 'low-sodium'],
    allergens: ['tree-nuts'],
    nutrition: { calories: 160, proteinGrams: 6, carbsGrams: 6, fatGrams: 14, fiberGrams: 3.5, sodiumMg: 0 },
    inStock: true,
    stockCount: 62,
    weightGrams: 454,
    ecoScore: 'B',
  },
  {
    id: 'prod-021',
    name: 'Sea Salt Crispy Chickpea Snacks',
    brand: 'Biena Crunchy Legumes',
    category: 'Snacks',
    price: 3.99,
    unit: '5 oz pouch',
    barcode: '01111000802',
    imageUrl: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 8 - Healthy Snacks & Nuts',
    aisleNumber: 8,
    shelfSection: 'Shelf 8B - High Protein Chips & Legumes',
    coordinates: { x: 91, y: 72 },
    dietaryFlags: ['vegan', 'gluten-free', 'dairy-free', 'nut-free'],
    allergens: [],
    nutrition: { calories: 130, proteinGrams: 6, carbsGrams: 18, fatGrams: 3.5, fiberGrams: 6, sodiumMg: 150 },
    inStock: true,
    stockCount: 54,
    weightGrams: 142,
    ecoScore: 'A',
  },
  {
    id: 'prod-022',
    name: 'Organic Fair-Trade 85% Dark Chocolate',
    brand: 'ChocoVerde Rainforest',
    category: 'Snacks',
    price: 3.49,
    unit: '3 oz bar',
    barcode: '01111000803',
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=400&auto=format&fit=crop&q=80',
    aisle: 'Aisle 8 - Healthy Snacks & Nuts',
    aisleNumber: 8,
    shelfSection: 'Shelf 8C - Artisan Chocolates',
    coordinates: { x: 92, y: 78 },
    dietaryFlags: ['vegan', 'gluten-free', 'keto'],
    allergens: [],
    nutrition: { calories: 210, proteinGrams: 3, carbsGrams: 14, fatGrams: 17, fiberGrams: 4, sodiumMg: 10 },
    inStock: true,
    stockCount: 75,
    weightGrams: 85,
    ecoScore: 'A',
  },
];
